server:
  port: 5444

dialogflow:
  project-id: cdsoft-faq
  location-id: europe-west3
  agent-id: d1b1313d-acb8-401b-9a15-92ed13475568
  language-code: iw
  end-point: dialogflow.googleapis.com:443

logging:
  level:
    root: INFO

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: flash.relampago@gmail.com
    password: ruxpbnlzjnxowyeb
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            protocols: TLSv1.2
  datasource:
    url: jdbc:mysql://eu-cdbr-west-03.cleardb.net:3306/heroku_d128fbed6b62405
    username: b5504d5a0db4a5
    password: e7c646d2
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
    defer-datasource-initialization: true
  sql:
    init:
      mode: always

email:
  from: no.reply@gmail.com
  to: barak.yedaya@gmail.com

integrator:
#  url: https://new-dave-cdsoft-integrator.herokuapp.com
  url: https://dc84-2a06-c701-bf63-6400-d55d-7c49-5c0f-8d9e.eu.ngrok.io